### ISSUE TITLE
Sparkline canvas is empty if page is loaded by AJAX

### ISSUE THREAD

**Issue by tim-peterson** [gwatts/jquery.sparkline#11]
Hi Gareth, thanks for such a great plugin. Its really easy to use!

My sparkline chart appears when I do a full page load but not if it is loaded by AJAX. What solves the problem is if also include the jQuery library in my AJAX page load. I'd rather not have to load jQuery as part of the AJAX request as that defeats the purpose of AJAX (cutting down on #/size of http requests).

This issue is not specific to my implementation of sparkline.js because cutting and pasting the demo code has the same problem.

I've tried many different kinds of script and html ordering but loading jQuery is the only thing that works.

I'm inexperienced with JavaScript/jQuery so I apologize if I'm not understanding something trivial.
thoughts?

thanks,
tim

**Comment by gwatts** [comment]
As per issue 6, a small demo of the problem would motivate a solution ;-)
