### ISSUE TITLE
IE 9 support

### ISSUE THREAD

**Issue by maen87** [gwatts/jquery.sparkline#12]
When im using IE9 im having an error:

SCRIPT5007: Object expected jquery.sparkline.min.js, line 4 character 3378

and it appears when using minified version and non minified version, any help ?

**Comment by gwatts** [comment]
I haven't been able to reproduce this so far; I've tested with IE6,7,8,9 and they all work for me - Perhaps you can try your site using browserstack.com for an independent test

**Comment by gwatts** [comment]
Please re-open if you can still reproduce this
