### ISSUE TITLE
Charts not drawn correctly when omnipotent.net/jquery.sparkline/ is down

### ISSUE THREAD

**Issue by jimdobjoern** [gwatts/jquery.sparkline#123]
Without changing anything on my code the charts are not paintet correctly anymore. I'm wondering if it happens since omnipotent.net/jquery.sparkline/ is down. Are there some known dependencies and a way how to fix it..?

**Comment by gwatts** [comment]
Download the library and install it onto your own webserver, or use Cloudflare's CDN service:
http://cdnjs.cloudflare.com/ajax/libs/jquery-sparklines/2.1.2/jquery.sparkline.min.js

omnipotent.net consists of a single personal server and is not intended to be used to host the plugin for third party sites - The download page explicitly states that.
