### ISSUE TITLE
Bar heights are not proportional to values

### ISSUE THREAD

**Issue by gnapse** [gwatts/jquery.sparkline#125]
I have noticed that bar heights are not proportional to the values they're supposed to represent. For instance, take a look at this screenshot of a quick bar chart I made on the 'try it out' section of your homepage.

![sparklines](https://cloud.githubusercontent.com/assets/15199/3922237/7cc1da74-23c8-11e4-91ec-2c3cf70378f0.png)

The values being represented are 84, 93 and 119. The first value (84) is larger than half the last and largest value (119). So I would expect the first bar to be more than half the height of the last bar.

I have a sense that this is not a bug, but that it works like this by design. If that's the case, I'd like to know what's the logic behind this reasoning. I'd also like to know if there's some configuration option I can pass to achieve the results I'm expecting. I made a quick search on the documentation, and on the  issues in this repository, and I've found nothing that could help me on this regard.

**Comment by gwatts** [comment]
Please see:
https://groups.google.com/forum/#!searchin/jquery-sparkline/relative/jquery-sparkline/yIzCCWtkUUY/cEJL4whX3xMJ

**Comment by gnapse** [comment]
So the solution is to pass the `chartRangeMin` option with value zero:

``` javascript
$('#selector').sparkline([84, 93, 119], {
  type: 'bar',
  chartRangeMin: 0,
});
```

Thanks!
