### ISSUE TITLE
Line Charts in Chrome 19 dont show line and spots

### ISSUE THREAD

**Issue by sychedelix** [gwatts/jquery.sparkline#13]
Can't render lines and sport when using Chrome 19.0.1084.52 and having the height set to 113 or upper.

canvas: 5,3,9,6,5,9,7,3,5,9,5,39,13,29,5,9,5,9,7,3,5,9,10,15

**Comment by gwatts** [comment]
I can't reproduce this with Chrome 19 on either Windows or OS X.

Please re-open with more details, including the US you're using and a specific example of a problem sparkline.
