### ISSUE TITLE
[enhancement?] river graphs

### ISSUE THREAD

**Issue by ericlowry** [gwatts/jquery.sparkline#137]
I need a line graph that fills the area between two points (high and low).

Like the "normal" range on the graph below (light blue, hard to see):

http://ian.umces.edu/ecocheck/forecast/chesapeake-bay/2010/overview/

Today I am painting a composite graph with a high line and a low line, but I really want the area between the lines to be filled.

**Comment by zoechi** [comment]
The link is broken

**Comment by ericlowry** [comment]
@zoechi here is a link to the image: http://ian.umces.edu/ecocheck/images/forecast_flow_graph_2010.png

Note: I figured out how to accomplish this with a composite graph, but I still thing it would be nice feature for folks who need it.
