### ISSUE TITLE
cannot get $.sparkline_display_visible(); to draw sparklines 

### ISSUE THREAD

**Issue by mojopollo** [gwatts/jquery.sparkline#14]
this is an awsome plugin,

I am having trouble getting $.sparkline_display_visible() to show my sparklines on display:none div's

I am using:
sparklines 2.0
jquery 1.7.1

I noticed in the code:
// jQuery 1.3.0 completely changed the meaning of :hidden :-/
$.fn.jquery < '1.3.0' 

If I change that to:
$.fn.jquery >= '1.3.0'

$.sparkline_display_visible() draws the graph without any issues, is this a typo or am I doing something wrong on my end. 

thank you for all your hard work!

**Comment by gwatts** [comment]
Please come up with a small self-contained example

**Comment by mojopollo** [comment]
``` html
<html>
<head>
<link rel="stylesheet" type="text/css" href="http://s3.amazonaws.com/tmpshare/bootstrap.css">
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript" src="http://s3.amazonaws.com/tmpshare/bootstrap.js"></script>
<script type="text/javascript" src="http://omnipotent.net/jquery.sparkline/2.0/jquery.sparkline.js"></script>
<body>

<nav class="subnav">
    <div class="container">
        <div class="row">
            <div class="span7">
                <ul class="nav nav-pills">
                    <li class="active"><a href="#all" data-toggle="tab">All</a></li>
                    <li><a class="pings-hidden" href="#others" data-toggle="tab">Others</a></li>
                </ul>
            </div>
        </div>
    </div>
</nav>

<div class="tab-content">

    <div class="tab-pane active" id="all">
            Graph 1: <div class="sparkline-graph"></div>
    </div>

    <div class="tab-pane" id="others">
            Graph 2: <div class="sparkline-graph"></div>
    </div>
</div>

<script>
    $('.sparkline-graph').sparkline([1,1,1,1,1,1,1,1,-1,1,1,1,-1,1,1,1,-1,-1,1,1], {
        type: 'bar'
    });
</script>

</body>
</html>
```

**Comment by gwatts** [comment]
There's two issues here:

1) I don't see any call to $.sparkline_display_visible() in bootstrap.js 
2) Your sparkline-graph tags need to contain some text, even if it's just &nbsp; for sparkline_display_visible() to work correctly.

Adding a call to $.sparkline_display_visible() in bootstrap.js line 662 and changing the tags to `<div class="sparkline-graph">&nbsp;</div>` causes it to work correctly for me

**Comment by mojopollo** [comment]
I can confirm that after adding the `&nbsp;` inside the divs and calling $.sparkline_display_visible() graphs display. Thank you for your help !

**Comment by gwatts** [comment]
Cool; glad I could help
