### ISSUE TITLE
Label axes 

### ISSUE THREAD

**Issue by dnlmelo** [gwatts/jquery.sparkline#157]
I missed the labels on axes, should put this in object : 
element.sparkline({
...
labelAxisV: String,
labelAxisH: String
.. 
});

**Comment by gwatts** [comment]
From the FAQ http://omnipotent.net/jquery.sparkline/#s-faq

> Why are there no axis labels/markers?
> 
> Sparklines are intended to be small enough to fit alongside a line of text, to give a quick impression of a trend or pattern and thus don't have the paraphernalia of full sized charts. As of version 2.0 you can  mouse over the sparklines to see the underlying data.
