### ISSUE TITLE
The sparkline chart is drawn on top of every UI element in my page in IE 9 browser

### ISSUE THREAD

**Issue by naveenc** [gwatts/jquery.sparkline#17]
Hi

We are using jquery sparkline to display the line chart it is working fine in in all version of IE except IE 9 
The issue is the graph will be drawn on top of all the other components in UI

the below is the sample code 

<span class="dynamicsparkline">loading...</span>
var $jx=jQuery.noConflict();

   $jx(function() {
        /*\* This code runs when everything has been loaded on the page _/
        /_ Inline sparklines take their values from the contents of the tag _/
       /_ $jx('.linechart').sparkline('html', {normalRangeMax:'80',lineWidth:'1',spotColor:'false'}); _/
        $jx(function() {
        /_\* This code runs when everything has been loaded on the page _/
        /_ Inline sparklines take their values from the contents of the tag */
        var myvalues =//so values;
        $jx('.dynamicsparkline').sparkline(myvalues,{normalRangeMax:'80',lineWidth:'1',spotColor:'false'});
    });
    });

please help me to solve this issue

This issue occurs only in IE 9

Thanks in advance

**Comment by gwatts** [comment]
Do you have a complete standalone demonstration of this problem i can look at?

**Comment by gwatts** [comment]
No response in 10 months == dead
