### ISSUE TITLE
valueSpots option does not work in HTML tag

### ISSUE THREAD

**Issue by pjd25** [gwatts/jquery.sparkline#194]
I have the following code:

<span class="sparklines" sparkValueSpots="{'0': '#ffffff'}"></span>

$('.sparklines').sparkline('html', {
    enableTagOptions: true});

But this does not display the valueSpots.

However if I include the valuespots option in the function, they do work:

$('.sparklines').sparkline('html', {
    enableTagOptions: true,
    valueSpots: '{'0': '#ffffff'}'});

I believe this is a bug that valueSpots option does not work when in a tag option.

**Comment by gwatts** [comment]
Works fine for me: https://jsfiddle.net/gwatts/wdhkLgds/2/

**Comment by pjd25** [comment]
Seems only for single values like in your example. How can we get this to work for say all values > 50?

In the normal options it would be {'50:': 'red'} which when converting to your example format would be {50::red} (note the double ::) but this doesn't work.
