### ISSUE TITLE
sparkline function on jquery selector not working?

### ISSUE THREAD

**Issue by ryancole** [gwatts/jquery.sparkline#25]
I'm doing the following, and it is not working:

``` javascript
var test = $('<span>');
test.sparkline([1,2,3,4,5,6,7,8,9]);
```

I notice nothing inserted into the object, both in the console and after appending it to the dom.

Yet, the following works with an element that already exists in the dom:

``` javascript
var test = $('#test');
test.sparkline([1,2,3,4,5,6]);
```

Why is the first way not working? Shouldn't it work just the same as the second method?

**Comment by gwatts** [comment]
You need two things:
a) To use a non-empty span
b) to call $.sparkline_display_visible() once you've inserted the element into the DOM

eg.

``` javascript
var test = $('<span>&nbsp;</span>');
test.sparkline([1,2,3,4,5,6,7,8,9]);
$('#somelocation').append(test);
$.sparkline_display_visible();
```
