### ISSUE TITLE
tweak for IE 10

### ISSUE THREAD

**Issue by nwbrown** [gwatts/jquery.sparkline#29]
Internet Explorer 10 needs a tiny tweak at line 2500 to prevent adding namespaces - insert additional condtion 
 && $.browser.msie.version < 10.0

2500  if ($.browser.msie && $.browser.msie.version < 10.0 && !document.namespaces.v) {
2501    document.namespaces.add('v', 'urn:schemas-microsoft-com:vml', '#default#VML');
2502 }

**Comment by gwatts** [comment]
Duplicate of https://github.com/gwatts/jquery.sparkline/pull/19
