### ISSUE TITLE
Suggestion on not making the target in a bullet graph show up

### ISSUE THREAD

**Issue by rjiang** [gwatts/jquery.sparkline#3]
There are some cases where there is not always a target value.

With that being said, I added the following code to the renderTarget function:

if (this.values[0] == '0') this.target.drawRect(-1000, -1000, 0, 0, '#000', '#000');

When the targetWidth is set to 0, it will draw something nothing.

However, this is a weak hack. Hopefully, you guys consider doing this right in the future. :D

Overall, a great package of visualizations! I love it!

**Comment by rjiang** [comment]
i meant to say: it will draw nothing not 'something nothing' :D

**Comment by gwatts** [comment]
Thanks for the suggestion - I'll see about being able to set target to null for a future version

**Comment by gwatts** [comment]
Checked in an update to master - Either the target and/or the performance values can now be set to null to omit them from the chart
