### ISSUE TITLE
null values are not considered in 'interactive' mode.

### ISSUE THREAD

**Issue by aadrian** [gwatts/jquery.sparkline#4]
The null values that might appear in the data, are not considered in the code that draws the interactivity.
This can be very easily shown with the following data in your interactive example:

``` javascript
width:100
height: 100
values: 5,6,7,9,9,null,null,null,5,3,2,2,4,6,7 
```

the red line is drawn correctly under the mouse in the first part, but after the nulls, the line has an offset proportional to the number of missing values (nulls).

**Comment by gwatts** [comment]
Fixed in master
