### ISSUE TITLE
Add export (svg) functionality/api

### ISSUE THREAD

**Issue by aadrian** [gwatts/jquery.sparkline#45]
Please add the possibility to export the rendered chart somehow.

One very useful one (since it can be easily converted to everything) would be a SVG export - it's done by many chart libraries, and they can even simulate it under IE8.

Thanks in advance.

**Comment by gwatts** [comment]
The plugin doesn't use SVG right now; only canvas and VML.
See https://github.com/gwatts/jquery.sparkline/issues/80
