### ISSUE TITLE
Certain values for line chart cause a floating orange dot

### ISSUE THREAD

**Issue by bones418** [gwatts/jquery.sparkline#46]
Browsers I know it impacts:
Chrome 22.0.1229.94
Firefox 15.0.1
IE 8

How to reproduce:
1) Goto the sparkline website: http://omnipotent.net/jquery.sparkline/#s-about
2) In the try-it-out section select a line chart and use the following values:  104,6,7,null,null,null,null
3) Notice the floating orange dot to the right of the sparkline

What I expect:
No floating orange dot.  Like in the case where you used these values for the sparkline:  14,6,7,null,null,null,null

I'm not sure why certain values create the floating dot, but it looks like a bug to me.  Thanks in advance for looking into this!

**Comment by gwatts** [comment]
The bug is it's attempting to place a marker on the final value of the chart, which is null in this case.  You can set spotColor to false as a temporary fix and I'll check something in that will automatically disable the final spot marker if the final value is null.

**Comment by gwatts** [comment]
Fix checked in.

**Comment by bondarde** [comment]
There seems still to be a similar bug when the first value is null. The displayed values are than shifted. For example with "null,1,2,6,3,7" as input: the label for "7" is displayed without a marker, with marked value of "7", the label shows "3".
