### ISSUE TITLE
A chart having three components ( "undefined" in IE and Firefox..Works fine with Chrome

### ISSUE THREAD

**Issue by Ankit1912** [gwatts/jquery.sparkline#49]
I have sparkline chart having three components (101, 0, 100). It plots perfectly on chrome but there is a "un" instead of the chart on IE and in Fire Fox. IE version is 7 and Fire fox version is 16.0.2

**Comment by Ankit1912** [comment]
Html :- 

<p>
Sparkline appears here: <span id="sparkline">&nbsp;</span>
</p>

javascript :-
// jsfiddle configured to load jQuery Sparkline 2.1
// http://omnipotent.net/jquery.sparkline/

// Values to render
var values = [99.51,0.00,0.49];

// Draw a sparkline for the #sparkline element
$('#sparkline').sparkline(values, {
    type: 'pie', 
          borderWidth: 0,
          height: '1.40em',
          disableTooltips: true,
          sliceColors: ['#088A08','#2E64FE','#FF8000'],
          offset: 180
});

Result :-
Sparkline appears here: undefined

**Comment by gwatts** [comment]
Can you add a link to your jsfiddle example please?

**Comment by Ankit1912** [comment]
http://jsfiddle.net/ankit1912/pQhCY/3/

**Comment by gwatts** [comment]
The jsfiddle works for me if i select jquery 1.8.2 or 1.6.2 - Something odd going on with the 1.7.2 version in that context for some reason

**Comment by Ankit1912** [comment]
I still see the same effect for both 1.8.2 and 1.6.2. Have you tested jsfidle in IE7 ?

**Comment by gwatts** [comment]
On closer inspection this looks like a bug with the pie chart rendering for IE when very small slices are present.

I've checked in a fix now - Please try this build when you have a chance: http://omnipotent.net/jquery.sparkline/builds/121117/jquery.sparkline.js

**Comment by Ankit1912** [comment]
This one is rendering the pie but it is not showing the smallest non zero slice (0.49 in the above example) - This is only on IE

**Comment by gwatts** [comment]
The small slice is there, it's just too small to render using VML - You can verify it's there by changing the size from 1.4em to 14.0em or whatever in your example

Closing as it appears fixed to me.
