### ISSUE TITLE
tooltip not always on top

### ISSUE THREAD

**Issue by SteveSchreiner** [gwatts/jquery.sparkline#5]
I'm running into situations where the chart tooltip is not on top of the chart.  Can a change be made to always give the tooltip a very high z-index?

**Comment by SteveSchreiner** [comment]
I used the tooltipContainer property and that seemed to work...

**Comment by gwatts** [comment]
I will include a default high z-index in the next release, but you can also supply a z-index via your page's stylesheet:

``` HTML
<style type="text/css">
  .jqstooltip { z-index: 1000; }
</style>
```

**Comment by gwatts** [comment]
z-index set in master
