### ISSUE TITLE
Wrong display of minimum value(s)

### ISSUE THREAD

**Issue by r-a-f** [gwatts/jquery.sparkline#51]
Minimum value from array are not displayed correctly (there is a gap).

See example:
http://jsfiddle.net/8thrB/
("20" is display like a zero because 20 is the smallest value from an array)

**Comment by GLC** [comment]
Anyone figure this out? I'm having the same issues with bar chart

**Comment by gwatts** [comment]
This is intentional to distinguish between minimum values and null values.  Null values are omitted from the chart, minimum values are displayed as a single pixel line

**Comment by GLC** [comment]
But visually this doesn't make any sense, I cant have a bar showing lets say 20,30,40, 90 and 20 showing up next to 30 as 1 pixel high. Is there anyway around this? I have been tooling around in the js to see if I could figure out the math, but I'm not sure. I really love the simplicity of this graphing system over any other.

**Comment by GLC** [comment]
But visually this doesn't make any sense, I cant have a bar showing lets say 20,30,40, 90 and 20 showing up next to 30 as 1 pixel high. Is there anyway around this? I have been tooling around in the js to see if I could figure out the math, but I'm not sure. I really love the simplicity of this graphing system over any other.

**Comment by GLC** [comment]
for some reason my comments are not posting on the github site anymore 
but anyway:

"But visually this doesn't make sense, I cant have a bar showing lets 
say 20,30,40, 90 and 20 showing up next to 30 as 1 pixel high. Is there 
anyway around this? I have been tooling around in the js to see if I 
could figure out the math, but I'm not sure. I really love the 
simplicity of this graphing system over any other. Toss me your paypal 
so I can treat you to lunch

**Comment by gwatts** [comment]
There's no way to change that behaviour at the moment, but you can fake it by setting the colour for the bar with the minimum value to the background color.

Eg. for your example add an option for colorMap: {20: '#fff'}

**Comment by gwatts** [comment]
I asked GitHub support to take a look at why your comments weren't showing up btw; should be fixed now.  Offer of lunch much appreciated, but not required :-)

**Comment by GLC** [comment]
Ah i got you so basically toss in a fake minimum value and 'hide' it, 
cool i love quick and easy solution.

Hey let me treat to you dinner, whats your paypal address?

**Comment by gwatts** [comment]
Well you'd use the real minimum value from your data and hide that.

No need for dinner, but if you find yourself in SF sometime I might take a beer ;-)

**Comment by gwatts** [comment]
Add an enhancement request to cover this feature https://github.com/gwatts/jquery.sparkline/issues/81
