### ISSUE TITLE
Tooltip is shown for the last value in series, for same values in the series 

### ISSUE THREAD

**Issue by saadgit** [gwatts/jquery.sparkline#58]
Is it a bug that:

Tooltip is shown for the last value in series, for same values in the series 

e.g 
...

enableTagOptions: true,
type: 'line',
tooltipFormat: '{{y}} [ {{y:val}} ]', 
tooltipValueLookups: {
   'val' : {1:"A", 2:"B", 3:"C", 2:"D"
}

...

The sparkline for it will show tooltip on mouseover as

A, D, C, D, where as it should be A, B, C, D

How can it be fixed?
##

**Comment by gwatts** [comment]
It's not a bug - It's because you're looking up by value, and two entries have the same value.

Instead you can implement a tooltipFormatter which can return whatever you want for each x value.

Take a look at this example for a hint: http://jsfiddle.net/gwatts/RsbHC/
