### ISSUE TITLE
script fails when dynamically loaded

### ISSUE THREAD

**Issue by joeenzminger** [gwatts/jquery.sparkline#6]
An exception gets thrown inside of the initStyles function when the script is loaded dynamically.  

This is because the following line:

$(initStyles);

will execute immediately if the dom is ready.  If it executes immediately, the addCss function has not yet been defined.  

The fix is to move $(initStyles); after addCss is properly defined.

**Comment by gwatts** [comment]
Thanks for the bug report.  If you can create a gist that demonstrates the bug, that would be useful too.

**Comment by tim-peterson** [comment]
@joeenzminger @gwatts i think I just noticed the same problem. I just posted this as an issue, #11, https://github.com/gwatts/jquery.sparkline/issues/11.

I will delete my issue if we are saying the same thing.

**Comment by tim-peterson** [comment]
@joeenzminger @gwatts, I tried moving the `$(initStyles);` after the `addCss()` method is defined within jquery.sparkline.js but still couldn't get dynamic page loading to work. 

I made a gist showing this, https://gist.github.com/2868211. Note that I changed jquery.sparkline.js at lines 375 and 586. Can you perhaps clarify in this gist to show how you think the code should look?

**Comment by paulbjensen** [comment]
I've managed to fix the issue, and submitted a pull request: https://github.com/gwatts/jquery.sparkline/pull/16

**Comment by listaction** [comment]
@joeenzminger @gwatts: it (moving $(initStyle) ) should work. Just tried it with include.

**Comment by naugtur** [comment]
@gwatts It would be nice if you could accepted the pull request and built distribution. please ;)

**Comment by gwatts** [comment]
Not forgotten; just haven't had time to work on a release recently - Hopefully I'll have a free weekend soon and will test & merge the outstanding updates.

Thanks for patches & patience :-)

**Comment by gwatts** [comment]
Fixed in master

**Comment by dodtsair** [comment]
Ran into this issue with the work I am doing.  When is the next release planned?

**Comment by gwatts** [comment]
Will hopefully have time to complete a release this coming weekend
