### ISSUE TITLE
jQuery 1.9.0 breaks Sparklines

### ISSUE THREAD

**Issue by Soupy** [gwatts/jquery.sparkline#60]
I believe that the use of '$.browser' in the plugin is causing an issue with jQuery 1.9.0.

**Comment by gwatts** [comment]
A fix has been checked into github, if you'd like to try it.

**Comment by Soupy** [comment]
I wish I could, but, the best that I can do is to test the final plugin since I would not have a clue as to how to build it from the source :( I'll have to wait for jquery.sparkline.js to test.

Thanks anyway for such a quick fix.

**Comment by Soupy** [comment]
Would it be possible for someone to create a "latest plugin" (jquery.sparkline.js) for me to test? I don' t know how to take the individual source scripts and pull them together and I can't find any instructions on how to do so.

**Comment by javadoug** [comment]
@Soupy
If you have a mac with GIT installed, from the terminal you can do this:
`git clone git://github.com/gwatts/jquery.sparkline.git`
`cd jquery.sparkline`
`make`

**Comment by Soupy** [comment]
Thanks for those instructions. Unfortunately (?) I don't have a mac. I ended up just taking the original jquery.sparkline.js source and making the changes manually and they seem to be working fine. Regards.
 Date: Fri, 25 Jan 2013 19:42:25 -0800

**Comment by javadoug** [comment]
that works. :)
I wonder why is has not updated the dist yet.

**Comment by gwatts** [comment]
I was hoping to have time to fold in some other updates prior to creating a new release, but that hasn't happened - Will be releasing a minor update today with just this fix

**Comment by javadoug** [comment]
Thank you.

**Comment by gwatts** [comment]
2.1.1 released.
