### ISSUE TITLE
Bower Component configuration support.

### ISSUE THREAD

**Issue by amanu** [gwatts/jquery.sparkline#70]
add "component.json" for Bower https://github.com/twitter/bower  to this project to facilitate users to easily integrate your sparkline component with all it's dependencies in projects (so far Bower seems the only widely used dependency manager for JavaScript components for the browser).

regards.

**Comment by soullivaneuh** [comment]
Sparkline Bower is already referenced on Bower components, but we get all the src, and not the compiled file.

There is a way to get the compiled file ?

Thanks.

**Comment by gwatts** [comment]
Closing this issue in favour of the discussion here: https://github.com/gwatts/jquery.sparkline/issues/92
