### ISSUE TITLE
Feature request: option to pre-process the data

### ISSUE THREAD

**Issue by sahuguet** [gwatts/jquery.sparkline#75]
Hi,

big fan of the framework.

There are two things I would like to do with the data before rendering it:
- reverse the order of the data
  e.g. [1,2,3] becomes [3,2,1]
- accumulate values
  e.g. [1,1,3,4] becomes [1,2,5,9]

Having a callback function to preprocess the value array before it is rendered should do the trick.

regards,

Arnaud

**Comment by gwatts** [comment]
Why do you need the plugin to do this, rather than just handling it from your own code before the sparkline() function is called?
