### ISSUE TITLE
In-compatibility: Jquery new versions.

### ISSUE THREAD

**Issue by miradnan** [gwatts/jquery.sparkline#87]
It doesn't work with jquery version 1.9.1 and so on... But it does work with 1.8.3

**Comment by gwatts** [comment]
The latest release definitely works with jQuery versions up to and including the current 1.x release (1.10.2).

Please post a link to a simple example of it not working after confirming you're using version 2.1.2 of the plugin

**Comment by miradnan** [comment]
Hi Gareth,

I was using version 2.0. I updated to 2.1.2 and its all working fine.

Thank you for your quick response.

Have a great day.

-Mir
