### ISSUE TITLE
Pie charts in IE 7/8 have undefined text when 0 values are present

### ISSUE THREAD

**Issue by y2chen** [gwatts/jquery.sparkline#9]
Using the pie chart in IE 7/8, if you have a value array with a 0 value present, like `[24,37,0,12]`, you'll get as many "undefined" text strings behind the pie chart as there are 0 values in the array. This seems like a new bug introduced in 2.0, as it wasn't around in 1.6.

**Comment by gwatts** [comment]
Fixed in master
