### ISSUE TITLE
[IE7, IE8] addCSS() throws "Invalid Argument" exception after 30+ calls to document.createStyleSheet()

### ISSUE THREAD

**Issue by AspNyc** [gwatts/jquery.sparkline#94]
Example: http://jsbin.com/iniGoxe/3

Kind of an obscure bug, but one that cropped up for us today when our new consulting company loaded one too many CSS files.  Basically, there's a known limitation in IE7 and IE8 where if more than 30 spreadsheets are loaded, it throws an "Invalid Argument" exception:
1. http://msdn.microsoft.com/en-us/library/ms531194%28VS.85%29.aspx
2. http://dean.edwards.name/weblog/2010/02/bug85/
3. http://stackoverflow.com/questions/3211991/does-ie-8-have-a-limit-on-number-of-stylesheets-per-page

Our workaround was to dynamically create a STYLE element and add it as a child of the HEAD element:

```
// http://paulirish.com/2008/bookmarklet-inject-new-css-rules/
addCSS = function(css) {
    var tag;
    //if ('\v' == 'v') /* ie only */ {
    if (document.createStyleSheet) {
        // Only workaround the cases that need it.
        if (document.styleSheets.length >= 30) {
            var styleNode = document.createElement('style');
            styleNode.type = "text/css";
            styleNode.styleSheet.cssText = css;
            document.getElementsByTagName('head')[0].appendChild(styleNode);
        }   
        else {
            document.createStyleSheet().cssText = css;
        }
    } else {
        tag = document.createElement('style');
        tag.type = 'text/css';
        document.getElementsByTagName('head')[0].appendChild(tag);
        tag[(typeof document.body.style.WebkitAppearance == 'string') /* webkit only */ ? 'innerText' : 'innerHTML'] = css;
    }
};
```

Does this make sense?

**Comment by gwatts** [comment]
Actually this is already fixed in the master branch as of July 30th:
https://github.com/gwatts/jquery.sparkline/commit/843dfd5e44cb6cc5e4d2d1a913215f74bf045dbb

It hasn't made it to a release as yet though

**Comment by AspNyc** [comment]
You guys are awesome -- thanks for the fix as well as the reply!
